CLASS zcl_mig_xco_gen DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.

    METHODS generate_query
      IMPORTING
        is_mfst
          TYPE zif_mig_types=>ty_art_mfst

        iv_request
          TYPE trkorr

        iv_execute
          TYPE abap_bool
          DEFAULT abap_false

      RAISING
        zcx_mig_analysis
        cx_xco_gen_put_exception.

     METHODS add_ddls
      IMPORTING
        io_put
          TYPE REF TO if_xco_cp_gen_d_o_put

        is_item
          TYPE zif_mig_types=>ty_art_item

        iv_class_name
          TYPE zif_mig_types=>ty_art_name

        iv_package
          TYPE devclass.

  PRIVATE SECTION.

    METHODS validate
      IMPORTING
        is_mfst
          TYPE zif_mig_types=>ty_art_mfst

        iv_request
          TYPE trkorr

      RAISING
        zcx_mig_analysis.


    METHODS add_clas
      IMPORTING
        io_put
          TYPE REF TO if_xco_cp_gen_d_o_put

        is_item
          TYPE zif_mig_types=>ty_art_item

        iv_package
          TYPE devclass.

ENDCLASS.

CLASS zcl_mig_xco_gen IMPLEMENTATION.

  METHOD generate_query.

    validate(
      is_mfst    = is_mfst
      iv_request = iv_request
    ).


    READ TABLE is_mfst-items
      WITH KEY
        art_type =
          zif_mig_types=>gc_art_clas

        art_role =
          zif_mig_types=>gc_art_query_prv

      INTO DATA(ls_clas).

    READ TABLE is_mfst-items
      WITH KEY
        art_type =
          zif_mig_types=>gc_art_ddls

        art_role =
          zif_mig_types=>gc_art_entity

      INTO DATA(ls_ddls).


    IF sy-subrc <> 0
       OR ls_clas-object_name IS INITIAL.

      RAISE EXCEPTION NEW zcx_mig_analysis(
        textid =
          zcx_mig_analysis=>analysis_failed

        program_name =
          is_mfst-source_program
      ).

    ENDIF.


    DATA(lo_env) =
      xco_cp_generation=>environment->dev_system(
          iv_request
      ).


    DATA(lo_put) =
      lo_env->create_put_operation( ).


    add_clas(
      io_put      = lo_put
      is_item     = ls_clas
      iv_package  = is_mfst-package
    ).

    add_ddls(
      io_put = lo_put

      is_item =  ls_ddls

      iv_class_name = ls_clas-object_name

      iv_package = is_mfst-package
    ).

    IF iv_execute = abap_true.

      lo_put->execute( ).

    ENDIF.

  ENDMETHOD.


  METHOD validate.

    IF is_mfst-status <>
         zif_mig_types=>gc_art_ready.

      RAISE EXCEPTION NEW zcx_mig_analysis(
        textid =
          zcx_mig_analysis=>analysis_failed

        program_name =
          is_mfst-source_program
      ).

    ENDIF.


    IF is_mfst-strategy <>
         zif_mig_types=>gc_svc_query.

      RAISE EXCEPTION NEW zcx_mig_analysis(
        textid =
          zcx_mig_analysis=>analysis_failed

        program_name =
          is_mfst-source_program
      ).

    ENDIF.


    IF is_mfst-package IS INITIAL
       OR iv_request IS INITIAL.

      RAISE EXCEPTION NEW zcx_mig_analysis(
        textid =
          zcx_mig_analysis=>analysis_failed

        program_name =
          is_mfst-source_program
      ).

    ENDIF.


    IF is_mfst-create_count <= 0
       OR is_mfst-block_count > 0.

      RAISE EXCEPTION NEW zcx_mig_analysis(
        textid =
          zcx_mig_analysis=>analysis_failed

        program_name =
          is_mfst-source_program
      ).

    ENDIF.


    LOOP AT is_mfst-items
      INTO DATA(ls_item)
      WHERE required = abap_true.

      IF ls_item-gen_state <>
           zif_mig_types=>gc_art_planned
         OR ls_item-gen_mode <>
              zif_mig_types=>gc_art_create.

        RAISE EXCEPTION NEW zcx_mig_analysis(
          textid =
            zcx_mig_analysis=>analysis_failed

          program_name =
            is_mfst-source_program
        ).

      ENDIF.

    ENDLOOP.

  ENDMETHOD.


  METHOD add_clas.

  DATA(lo_spec) =
    io_put->for-clas->add_object(
      is_item-object_name
    )->set_package(
      iv_package
    )->create_form_specification( ).


  lo_spec->set_short_description(
    'Generated MIG query provider'
  ).


  lo_spec->definition->set_create_visibility(
    xco_cp_abap_objects=>visibility->public
  ).


  lo_spec->definition->add_interface(
    'IF_RAP_QUERY_PROVIDER'
  ).


  lo_spec->implementation->add_method(
    'IF_RAP_QUERY_PROVIDER~SELECT'
  )->set_source(
    VALUE #(
      ( |" Generated by MIG.| )
    )
  ).

ENDMETHOD.

METHOD add_ddls.

  DATA(lo_spec) =
    io_put->for-ddls->add_object(
      is_item-object_name
    )->set_package(
      iv_package
    )->create_form_specification( ).


  lo_spec->set_short_description(
    'Generated MIG custom entity'
  ).


  DATA(lo_entity) =
    lo_spec->add_custom_entity( ).


  lo_entity->add_annotation(
    'EndUserText.label'
  )->value->build(
  )->add_string(
    'Generated MIG query entity'
  ).


  DATA(lv_provider) =
    |ABAP:{ iv_class_name }|.


  lo_entity->add_annotation(
    'ObjectModel.query.implementedBy'
  )->value->build(
  )->add_string(
    lv_provider
  ).


  DATA(lo_key) =
    lo_entity->add_field(
      xco_cp_ddl=>field(
        'RecordId'
      )
    ).


  lo_key->set_key( ).

  lo_key->set_type(
    xco_cp_abap_dictionary=>built_in_type->char(
      32
    )
  ).

  lo_key->add_annotation(
    'EndUserText.label'
  )->value->build(
  )->add_string(
    'Record ID'
  ).


  DATA(lo_text) =
    lo_entity->add_field(
      xco_cp_ddl=>field(
        'ResultText'
      )
    ).


  lo_text->set_type(
    xco_cp_abap_dictionary=>built_in_type->char(
      120
    )
  ).

  lo_text->add_annotation(
    'EndUserText.label'
  )->value->build(
  )->add_string(
    'Result Text'
  ).

ENDMETHOD.

ENDCLASS.
