CLASS zcl_mig_ai_prompt_builder DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.

    INTERFACES
      zif_mig_ai_prompt_builder.

ENDCLASS.



CLASS zcl_mig_ai_prompt_builder IMPLEMENTATION.


  METHOD zif_mig_ai_prompt_builder~build.


    CLEAR rs_prompt.


    "==========================================================
    " Validate
    "==========================================================
    IF iv_markdown IS INITIAL.

      RAISE EXCEPTION TYPE zcx_mig_analysis
        EXPORTING
          textid =
            zcx_mig_analysis=>analysis_failed
          program_name =
            iv_program_name.

    ENDIF.


    "==========================================================
    " System prompt
    "==========================================================
    rs_prompt-system_prompt =
      |You are a SAP ABAP modernization analysis assistant.| &&
      cl_abap_char_utilities=>newline &&
      cl_abap_char_utilities=>newline &&

      |You receive a technical document generated by a deterministic static-analysis engine from a legacy ABAP report.| &&
      cl_abap_char_utilities=>newline &&

      |Treat that technical document as the only source of technical facts.| &&
      cl_abap_char_utilities=>newline &&
      cl_abap_char_utilities=>newline &&

      |STRICT RULES:| &&
      cl_abap_char_utilities=>newline &&

      |1. Do not invent ABAP programs, includes, tables, fields, routines, function modules, BAPIs, methods, ALV objects or execution paths.| &&
      cl_abap_char_utilities=>newline &&

      |2. Only claim a technical fact when it is supported by the supplied document.| &&
      cl_abap_char_utilities=>newline &&

      |3. Business purpose is an inference, not a parser fact. Clearly label it as inferred and provide a confidence level.| &&
      cl_abap_char_utilities=>newline &&

      |4. Do not interpret the static application flow as a complete runtime control-flow graph.| &&
      cl_abap_char_utilities=>newline &&

      |5. Dynamic runtime values, dynamic SQL, dynamic calls, complex GUI behavior and missing data-flow relationships must be marked for manual review when evidence is insufficient.| &&
      cl_abap_char_utilities=>newline &&

      |6. Do not recommend COMMIT WORK inside RAP behavior logic. Transaction handling must respect RAP save sequencing.| &&
      cl_abap_char_utilities=>newline &&

      |7. Recommendations must distinguish deterministic findings from AI inference.| &&
      cl_abap_char_utilities=>newline &&

      |8. Prefer SAP RAP, CDS view entities and Fiori Elements concepts when suggesting a target modernization architecture.| &&
      cl_abap_char_utilities=>newline &&

      |9. Generated code is a suggestion only and must never be described as production-ready without manual review.| &&
      cl_abap_char_utilities=>newline &&

      |10. Return JSON only. Do not wrap the JSON in Markdown code fences.|.


    "==========================================================
    " User Prompt
    "==========================================================
    rs_prompt-user_prompt =
      |Analyze the following legacy ABAP technical document.| &&
      cl_abap_char_utilities=>newline &&
      cl_abap_char_utilities=>newline &&

      |PROGRAM: { iv_program_name }| &&
      cl_abap_char_utilities=>newline &&
      cl_abap_char_utilities=>newline &&

      `Your goals are:` &&
      cl_abap_char_utilities=>newline &&

      `- explain what the legacy application appears to do,` &&
      cl_abap_char_utilities=>newline &&

      `- explain the legacy processing flow in developer-friendly language,` &&
      cl_abap_char_utilities=>newline &&

      `- identify modernization risks,` &&
      cl_abap_char_utilities=>newline &&

      `- propose a migration sequence,` &&
      cl_abap_char_utilities=>newline &&

      `- propose a target SAP RAP / CDS / Fiori architecture,` &&
      cl_abap_char_utilities=>newline &&

      `- optionally provide focused code suggestions when the evidence is sufficient.` &&
      cl_abap_char_utilities=>newline &&
      cl_abap_char_utilities=>newline &&

      `Return exactly one JSON object using this structure:` &&
      cl_abap_char_utilities=>newline &&
      cl_abap_char_utilities=>newline &&

      `{` &&
      cl_abap_char_utilities=>newline &&

      `  "applicationSummary": "string",` &&
      cl_abap_char_utilities=>newline &&

      `  "businessPurposeInference": {` &&
      cl_abap_char_utilities=>newline &&

      `    "text": "string",` &&
      cl_abap_char_utilities=>newline &&

      `    "confidence": "HIGH|MEDIUM|LOW",` &&
      cl_abap_char_utilities=>newline &&

      `    "reasoning": "string"` &&
      cl_abap_char_utilities=>newline &&

      `  },` &&
      cl_abap_char_utilities=>newline &&

      `  "legacyFlowExplanation": "string",` &&
      cl_abap_char_utilities=>newline &&

      `  "risks": [` &&
      cl_abap_char_utilities=>newline &&

      `    {` &&
      cl_abap_char_utilities=>newline &&

      `      "title": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "description": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "severity": "INFO|LOW|MEDIUM|HIGH|CRITICAL",` &&
      cl_abap_char_utilities=>newline &&

      `      "confidence": "HIGH|MEDIUM|LOW",` &&
      cl_abap_char_utilities=>newline &&

      `      "evidence": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "manualReview": true` &&
      cl_abap_char_utilities=>newline &&

      `    }` &&
      cl_abap_char_utilities=>newline &&

      `  ],` &&
      cl_abap_char_utilities=>newline &&

      `  "modernizationPlan": [` &&
      cl_abap_char_utilities=>newline &&

      `    {` &&
      cl_abap_char_utilities=>newline &&

      `      "sequence": 1,` &&
      cl_abap_char_utilities=>newline &&

      `      "title": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "description": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "targetLayer": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "confidence": "HIGH|MEDIUM|LOW",` &&
      cl_abap_char_utilities=>newline &&

      `      "manualReview": true` &&
      cl_abap_char_utilities=>newline &&

      `    }` &&
      cl_abap_char_utilities=>newline &&

      `  ],` &&
      cl_abap_char_utilities=>newline &&

      `  "targetArchitecture": [` &&
      cl_abap_char_utilities=>newline &&

      `    {` &&
      cl_abap_char_utilities=>newline &&

      `      "legacyComponent": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "targetComponent": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "rationale": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "confidence": "HIGH|MEDIUM|LOW"` &&
      cl_abap_char_utilities=>newline &&

      `    }` &&
      cl_abap_char_utilities=>newline &&

      `  ],` &&
      cl_abap_char_utilities=>newline &&

      `  "codeSuggestions": [` &&
      cl_abap_char_utilities=>newline &&

      `    {` &&
      cl_abap_char_utilities=>newline &&

      `      "title": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "targetObject": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "suggestion": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "code": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "language": "ABAP",` &&
      cl_abap_char_utilities=>newline &&

      `      "confidence": "HIGH|MEDIUM|LOW",` &&
      cl_abap_char_utilities=>newline &&

      `      "manualReview": true` &&
      cl_abap_char_utilities=>newline &&

      `    }` &&
      cl_abap_char_utilities=>newline &&

      `  ],` &&
      cl_abap_char_utilities=>newline &&

      `  "manualReview": [` &&
      cl_abap_char_utilities=>newline &&

      `    {` &&
      cl_abap_char_utilities=>newline &&

      `      "title": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "description": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "severity": "INFO|LOW|MEDIUM|HIGH|CRITICAL",` &&
      cl_abap_char_utilities=>newline &&

      `      "confidence": "HIGH|MEDIUM|LOW",` &&
      cl_abap_char_utilities=>newline &&

      `      "evidence": "string",` &&
      cl_abap_char_utilities=>newline &&

      `      "manualReview": true` &&
      cl_abap_char_utilities=>newline &&

      `    }` &&
      cl_abap_char_utilities=>newline &&

      `  ]` &&
      cl_abap_char_utilities=>newline &&

      `}` &&
      cl_abap_char_utilities=>newline &&
      cl_abap_char_utilities=>newline &&

      `TECHNICAL DOCUMENT START` &&
      cl_abap_char_utilities=>newline &&

      `============================================================` &&
      cl_abap_char_utilities=>newline &&

      iv_markdown &&
      cl_abap_char_utilities=>newline &&

      `============================================================` &&
      cl_abap_char_utilities=>newline &&

      `TECHNICAL DOCUMENT END`.


  ENDMETHOD.


ENDCLASS.
