INTERFACE zif_mig_ui_contract PUBLIC.
  CONSTANTS gc_version TYPE i VALUE 1.
  TYPES:
    BEGIN OF ty_issue,
      severity TYPE c LENGTH 1,
      code TYPE c LENGTH 30,
      target TYPE string,
      message TYPE string,
    END OF ty_issue,
    tt_issue TYPE STANDARD TABLE OF ty_issue WITH EMPTY KEY,
    BEGIN OF ty_column,
      property TYPE string,
      label TYPE string,
      edm_type TYPE string,
      position TYPE i,
      is_key TYPE abap_bool,
      currency_property TYPE string,
      unit_property TYPE string,
    END OF ty_column,
    tt_column TYPE STANDARD TABLE OF ty_column WITH EMPTY KEY,
    BEGIN OF ty_filter,
      source_parameter TYPE string,
      property TYPE string,
      provider_parameter TYPE string,
      kind TYPE string,
      required TYPE abap_bool,
      value_help_supported TYPE abap_bool,
    END OF ty_filter,
    tt_filter TYPE STANDARD TABLE OF ty_filter WITH EMPTY KEY,
    BEGIN OF ty_sort,
      property TYPE string,
      descending TYPE abap_bool,
    END OF ty_sort,
    tt_sort TYPE STANDARD TABLE OF ty_sort WITH EMPTY KEY,
    BEGIN OF ty_config,
      contract_version TYPE i,
      analysis_id TYPE sysuuid_c32,
      source_program TYPE string,
      app_title TYPE string,
      template TYPE string,
      odata_version TYPE string,
      status TYPE string,
      runtime_check TYPE string,
      service_root_url TYPE string,
      metadata_url TYPE string,
      entity_set TYPE string,
      custom_entity TYPE string,
      service_definition TYPE string,
      service_binding TYPE string,
      query_provider TYPE string,
      read_only TYPE abap_bool,
      table_supported TYPE abap_bool,
      filter_supported TYPE abap_bool,
      chart_supported TYPE abap_bool,
      columns TYPE tt_column,
      filters TYPE tt_filter,
      default_sort TYPE tt_sort,
      issues TYPE tt_issue,
    END OF ty_config.
ENDINTERFACE.
